### ISSUE TITLE
Keycloak Setting Issue

### ISSUE THREAD

**Issue by pachori91** [datakaveri/iudx-aaa-server#229]
Hi Team

I have setup keycloak(14.0.1) instance on my local running on http://{ip}:8080 by following https://github.com/datakaveri/iudx-deployment/tree/master/Docker-Swarm-deployment/single-node/keycloak.

Further after keycloak setup i have provided required info in config.json file for auth server as below by following https://github.com/datakaveri/iudx-aaa-server/blob/main/configs/config-example.json-
"keycloakOptions":{
        "keycloakHost": "{ip}",
        "keycloakPort": 8080,
        "keycloakRealm": "{realm-created}",
        "keycloakSite": "http://{ip}:8080/auth/realms/{realmname}",
        "keycloakUrl": "http://{ip}:8080/**auth**",
        "keycloakTokenUri": "/auth/realms/{realmname}/protocol/openid-connect/token",
        "keycloakAdminClientId": "adminclient",
        "keycloakAdminClientSecret": "{secret}",
        "keycloakAdminPoolSize": "10",
        "keycloakAaaClientId": "normalclient",
        "keycloakAaaClientSecret": "{secret}",
        "keycloakJwtLeeway": 90
      }

but i am getting error as below while starting My Auth server -
**Not Found: {"error":"RESTEASY003210: Could not find resource for full path: http://{ip}:8080/auth/realms/{realmname}/.well-known/openid-configuration"}"**

can you please help me here for same.

Thanks
Deepak Kumar

**Comment by ThorodanBrom** [comment]
Hello @pachori91

There are a few things that you can do to help us debug the issue:
- See if you are getting a response when you try to go to `http://{ip}:8080/auth/realms/{realmname}/.well-known/openid-configuration` in a browser
- The auth server works best when the Keycloak instance is running on trusted HTTPS. If possible, please try to configure HTTPS for your Keycloak instance. You can either follow the instructions [here](https://www.keycloak.org/docs/14.0/server_installation/#enabling-ssl-https-for-the-keycloak-server) or use something like NGINX + Let's Encrypt.

Let us know if you are able to do the above. Meanwhile, we will try our best to see if any of the issues can be resolved on our end.

**Comment by ThorodanBrom** [comment]
Closing issue since the working of the auth server has changed significantly since version 5.0.0
