### ISSUE TITLE
Need Comfiguration Step to setup IUDX admin

### ISSUE THREAD

**Issue by pachori91** [datakaveri/iudx-aaa-server#230]
Hi Team,

I have done with setup IUDX(3.5.0) AUTH, Catalogue, Resoource Server on my local.

Now i need to create Organization, Create/update provider by using Auth server's admin APIs.
To call These API's i need Iudx Admin's access token from keycloak.

SO what all the step i have to follow on keycloak or auth server to configure IUDX Admin user.
Can you please help me for same.

Thanks
Deepak Kumar

**Comment by ThorodanBrom** [comment]
https://github.com/datakaveri/iudx-aaa-server/issues/224#issuecomment-1233740199

**Comment by ThorodanBrom** [comment]
https://github.com/datakaveri/iudx-aaa-server/issues/224#issuecomment-1233862487

**Comment by ThorodanBrom** [comment]
Closing issue since the working of the auth server has changed significantly since version 5.0.0
