### ISSUE TITLE
How to set access policy for IUDX Consumer

### ISSUE THREAD

**Issue by pachori91** [datakaveri/iudx-aaa-server#271]
Hi Team,

Thanks for your continuous support.

**Below i am sharing my understanding towards how an IUDX provider can set access policy for consumer**

1. There could two type(Secure/Open) of Resource group be uploaded on IUDX Catalogue Server.
2. To Access Opened Resource Group's data , Access policy don't need to be set by IUDX Provider for Consumer.
3. But to Access Secured Reosurce Group's data, Access policy must be set by IUDX Provider for Counsumer
4. A provider can set access policy for consumer either by calling [Create Policy API](https://authorization.iudx.org.in/apis#tag/Policies-APIs/operation/post-auth-v1-policies) or by Using UI as explained [HERE](https://docs.iudx.org.in/docs/provider/provider_manage_policies/).

**Below are my further query-**
1. First of all please let me know if my understanding mentioned above is incorrect at any point?
2. How an IUDX Consumer can request to get Access for data of the Secured Resource Group. I mean how IUDX Provider will  know about Consumer who is interested to access Secured Resource Group data?

Thanks & Regard's
Deepak Kumar

**Comment by ThorodanBrom** [comment]
Hello @pachori91 

1. Your understanding of access policies is correct
2. An IUDX Consumer can notify their interest in a policy for a secure resource to the concerned IUDX Provider by using the **[Notification APIs/Access Request APIs](https://authorization.iudx.org.in/apis#tag/Notifications-APIs)**
    - A Consumer will find the resource they are interested in and make an access request using the [Create Access Requests API](https://authorization.iudx.org.in/apis#tag/Notifications-APIs/operation/post-auth-v1-policies-requests)
    - The Provider may view the list of access requests they have received using the [List Access Requests API](https://authorization.iudx.org.in/apis#tag/Notifications-APIs/operation/get-auth-v1-policies-requests)
    - The Provider can then choose to **approve the access request** - approving it will result in a policy being created for the Consumer for the resource. They may also choose to **reject the request instead**. Both these operations would be performed using the [Update Access Requests API](https://authorization.iudx.org.in/apis#tag/Notifications-APIs/operation/put-auth-v1-policies-requests)

I hope this answers your questions.

**Comment by pachori91** [comment]
@ThorodanBrom 
 
 Thanks for your reply, its realy helpfull for me.

**One more query regarding access policy management-**

- As an User with role Provider can i use **IUDX Portal** as mentioned [HERE](https://docs.iudx.org.in/docs/provider/provider_manage_policies/) to manage access policies for different Cosnumer?

Thanks
Deepak Kumar

**Comment by ThorodanBrom** [comment]
Hello @pachori91

Yes, if you are a registered and authorized provider on the IUDX system, you can access the provider panel at https://publisher.iudx.org.in and manage policies for consumers.

**Comment by pachori91** [comment]
Hello @ThorodanBrom 

Thanks for your reply, furhter i have one more query.

**My Use Case:** 
Suppose i registered myself as provider on IUDX Portal. So as an IUDX Provider user i have clientid, clientsecret and userid in my hand.
And now I want to write an script to set Access policy for Consumer who are interested for my Resource Data.
In this Script i need to use [Create Access Requests](https://authorization.iudx.org.in/apis#tag/Notifications-APIs/operation/post-auth-v1-policies-requests) API.  But as per documentation, the Create Access Request API Needs Bearer token for authorization purpose.

**Can you please help me here how can i get Bearer token with ClientId, ClientSecret & Userid which i have as an provider user on IUDX portal? Or please let me know if i will have any other information from IUDX protal which can help me to generate desired bearer token?**

Thanks
Deepak Kumar

**Comment by ThorodanBrom** [comment]
Hello @pachori91 

- Unfortunately, at this time, **bearer tokens can only be obtained using a browser flow with Keycloak**. In IUDX, we use the [Authorization Code Flow](https://www.keycloak.org/docs/latest/server_admin/#_oidc-auth-flows-authorization) ([see here too](https://www.keycloak.org/docs/latest/securing_apps/#authorization-code)) on Keycloak for login, so getting bearer tokens via a script is not possible. 
- The client ID and client secret flow is only used for getting IUDX access tokens, and cannot be used to get Keycloak bearer tokens. (The only 'scriptable' IUDX AAA API is `/auth/v1/token` to get IUDX access tokens using client ID, client secret)
- If you have your own deployment of the IUDX system, you may choose to enable the [Direct Access Grants] login flow in Keycloak (https://www.keycloak.org/docs/latest/server_admin/#_oidc-auth-flows-direct) for the `account` client. This will allow you to get tokens in a script. However, Keycloak [discourages](https://www.keycloak.org/docs/latest/securing_apps/#_resource_owner_password_credentials_flow) using this OIDC flow.

**Comment by ThorodanBrom** [comment]
Closing issue since the working of the auth server has changed significantly since version 5.0.0
